# --- build
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

# --- setuptools
[tool.setuptools]
#py-modules = ["parnet"]
packages = ["parnet"]

# --- project
[project]
version = "0.0.1"

name = "parnet"
authors = [{ name = "Marc Horlacher", email = "marc.horlacher@gmail.com" }]
description = "A description of the project."

readme = "README.md"
requires-python = ">=3.10,<3.11"
# keywords = ["one", "two"]
license = { file = "LICENSE" }

# Help categorize the project and make it easier for users and tools (such as PyPI and
# package managers) to discover, filter, and understand the project's purpose, audience,
# and compatibility.
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

#dependencies = []
dependencies = [
    "pip >=25.1",
    "ipykernel >=6.29",
    "pyarrow >=17.0,<21.0",
    "pandas >=2.0,<2.4",
    "numpy >=1.26,<2.0",
    "click >=8.2,<9.0",
    "gin-config ==0.5.0",
    "ipython >=8.37,<9.0",
    "pyyaml >=6.0,<7.0",
    "rich >=14.0,<15.0",
    "datasets >=3.6,<4.0",
    "transformers >=4.40,<5",
    "jaxtyping >=0.3.2,<0.4",
    "lightning >=2.3",
    "lightning-utilities >=0.14,<0.15",
    "biopython >=1.83,<1.85",
    "pybigwig >=0.3.22,<0.4",
    "pybedtools >=0.12.0,<0.13",
    "sequence-models >=1.8,<2.0",
    "tensorboard >=2.16,<2.17",
    "tensorflow >=2.16,<2.17",
    "torch ==2.5.1",
]

[project.optional-dependencies]
gpu = [
    "tensorflow[and-cuda] >=2.16,<2.17",
]

dev = [
    "ruff >=0.11,<1.0",
    "pytest >=8.4,<9",
    "mkdocstrings-python >=1.16,<2.0",
    "mkdocs >=1.6,<2.0",
    "mkdocs-material >=9.6,<10.0",
    "pytest >=8.4,<9",
    "pytest-cov >=6.0,<7.0",
    "pre-commit >=4.0,<5.0",
    "mypy >=1.11,<2.0",
]

[project.scripts]
parnet = "parnet.__main__:main"


# --- ruff
[tool.ruff]
line-length = 120
indent-width = 4
lint.pydocstyle.convention = "google"
format.quote-style = "single"
format.indent-style = "space"
