# --- build
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

# --- setuptools
[tool.setuptools]
py-modules = ["parnet"]

# --- project
[project]
version = "0.0.1"

name = "parnet"
authors = [{ name = "Marc Horlacher", email = "marc.horlacher@gmail.com" }]
description = "A description of the project."

readme = "README.md"
#requires-python = ">=3.8"
requires-python = ">=3.10,<3.13"
# keywords = ["one", "two"]
license = { file = "LICENSE" }

# Help categorize the project and make it easier for users and tools (such as PyPI and
# package managers) to discover, filter, and understand the project's purpose, audience,
# and compatibility.
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    'mkdocs',
    'mkdocstrings[python]',
    'mkdocs-material',
    'gin_config>=0.5.0',
    'lightning>=2.1.2',
    'biopython==1.83',
    'click>=8.1.7',
    'tensorflow==2.16.1',
    'tensorflow-datasets==4.9.3',
    'torch',
    'pandas',
    'datasets',
    'pybigwig',
    'pybedtools',
    'ipykernel',
    'ipython'
]


[project.scripts]
parnet = "parnet.__main__:main"


# --- ruff
[tool.ruff]
line-length = 120
indent-width = 4
lint.pydocstyle.convention = "google"
format.quote-style = "single"
format.indent-style = "space"


[tool.pixi.project]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
parnet = { path = ".", editable = true }

[tool.pixi.tasks]
